### ISSUE TITLE
[Bug]: initConfig  log shard replicas 

### ISSUE THREAD

**Issue by wanglei4687** [matrixorigin/matrixone-operator#265]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

### Actual Behavior
```yaml
apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: mo
  namespace: wanglei
spec:
  imageRepository: matrixorigin/matrixone
  version: nightly-63835b83
  logService:
    replicas: 3
    initialConfig:
      logShards: 1
      dnShards: 1
      logShardReplicas: 1
    sharedStorage:
      fileSystem:
        path: test/bucket
    volume:
      size: 10Gi
  dn:
    replicas: 1
    # cacheVolume specifies a dedicated volume for DN's local cache
    cacheVolume:
      size: 10Gi
  tp:
    replicas: 1
    # cacheVolume specifies a dedicated volume for CN's local cache
    cacheVolume:
      size: 10Gi
```

status:

```
[root@mo-srv-129 wanglei]# k get po -n wanglei
NAME       READY   STATUS             RESTARTS      AGE
mo-dn-0    0/1     CrashLoopBackOff   3 (75s ago)   2m36s
mo-log-0   0/1     CrashLoopBackOff   3 (55s ago)   3m8s
mo-log-1   0/1     CrashLoopBackOff   3 (80s ago)   3m8s
mo-log-2   0/1     CrashLoopBackOff   2 (38s ago)   3m8s
```

### Additional information

```
{"level":"ERROR","time":"2022/10/21 06:07:50.263818 +0000","name":"hakeeper-client","caller":"morpc/client.go:306","msg":"gc inactive backends task stopped"}
{"level":"INFO","time":"2022/10/21 06:07:50.268995 +0000","name":"LogService","caller":"logservice/service_commands.go:116","msg":"heartbeat worker stopped","uuid":"00000000-0000-0000-0000-000000000000"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x16f637c]

goroutine 368 [running]:
github.com/matrixorigin/matrixone/pkg/logservice.(*hakeeperClient).request(_, {_, _}, {0x0, 0x7, {{0x0, 0x0}, 0x0, 0x0, 0x0, ...}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:486 +0x7c
github.com/matrixorigin/matrixone/pkg/logservice.(*hakeeperClient).sendHeartbeat(0x0?, {0x28050e0?, 0xc0005b9920?}, {0x0, 0x7, {{0x0, 0x0}, 0x0, 0x0, 0x0, ...}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:464 +0x9f
github.com/matrixorigin/matrixone/pkg/logservice.(*hakeeperClient).sendLogHeartbeat(0x1?, {0x28050e0, 0xc0005b9920}, {{0xc002ccc8d0, 0x24}, {0xc000059c50, 0x2a}, {0xc000059cb0, 0x2a}, {0xc000720030, ...}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:452 +0x150
github.com/matrixorigin/matrixone/pkg/logservice.(*managedHAKeeperClient).SendLogHeartbeat(0xc002acac60, {0x28050e0, 0xc0005b9920}, {{0xc002ccc8d0, 0x24}, {0xc000059c50, 0x2a}, {0xc000059cb0, 0x2a}, {0xc000720030, ...}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:246 +0xe8
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).heartbeat(0xc0003263c0, {0x2805118?, 0xc000471b00?})
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/service_commands.go:155 +0x46b
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).heartbeatWorker(0xc0003263c0, {0x2805118, 0xc000471b00})
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/service_commands.go:126 +0x147
github.com/matrixorigin/matrixone/pkg/logservice.NewService.func5({0x2805070, 0xc0002fd8c0})
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/service.go:155 +0xd5
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:257 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:252 +0x12c
```

```
{"level":"WARN","time":"2022/10/21 06:14:36.540369 +0000","name":"gossip","caller":"registry/gossip_logger.go:44","msg":"memberlist: Failed to send gossip to 100.103.231.158:32002: write udp 100.103.231.175:32002->100.103.231.158:32002: use of closed network connection"}
{"level":"ERROR","time":"2022/10/21 06:14:36.540424 +0000","name":"LogService","caller":"logservice/service.go:90","msg":"failed to create log store","uuid":"00000000-0000-0000-0000-000000000000","error":"lookup mo-log-0.mo-log-headless.wanglei.svc on 10.96.0.10:53: no such host"}
panic: lookup mo-log-0.mo-log-headless.wanglei.svc on 10.96.0.10:53: no such host

goroutine 1 [running]:
main.startLogService(0xc00044c000, 0xc0001aa000?, {0x2812520, 0xc00002cea0}, {0x283cee0, 0xc00079a120})
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:204 +0x233
main.startService(0xc00044c000, 0xc0001a4070?)
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:122 +0x3d4
main.main()
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:76 +0x278
```
