### ISSUE TITLE
[Bug]: Cannot complete reconcile if `overlay` does not include fields that have default value

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone-operator#301]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id (e.g. v0.1.0 or 8b23a93): v0.6.0

### Actual Behavior

Set the following overlay will cause controller cannot complete reconcile:

```
    overlay:
      volumes:
      - name: cert
        secret:
          secretName: sql-cert
```

The reason is that k8s will set defaultMode for `volume`, the volume in podTemplate would be like:

```
      volumes:
      - name: cert
        secret:
          secretName: sql-cert
          defaultMode: 420
```

Thus the desired spec will always differ with the computed spec.

### Expected Behavior

The default value set by k8s should be ignore when compare diffs
